# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\"^\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x1f\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\r.FoodCategory\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\".\n\x12\x46oodRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"F\n\x16RecommendationResponse\x12,\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x13.FoodRecommendation*9\n\x0c\x46oodCategory\x12\x0b\n\x07\x43HINESE\x10\x00\x12\x0e\n\nHAMBURGUER\x10\x01\x12\x0c\n\x08JAPANESE\x10\x02\x32O\n\x0fRecommendations\x12<\n\tRecommend\x12\x16.RecommendationRequest\x1a\x17.RecommendationResponseb\x06proto3')

_FOODCATEGORY = DESCRIPTOR.enum_types_by_name['FoodCategory']
FoodCategory = enum_type_wrapper.EnumTypeWrapper(_FOODCATEGORY)
CHINESE = 0
HAMBURGUER = 1
JAPANESE = 2


_RECOMMENDATIONREQUEST = DESCRIPTOR.message_types_by_name['RecommendationRequest']
_FOODRECOMMENDATION = DESCRIPTOR.message_types_by_name['FoodRecommendation']
_RECOMMENDATIONRESPONSE = DESCRIPTOR.message_types_by_name['RecommendationResponse']
RecommendationRequest = _reflection.GeneratedProtocolMessageType('RecommendationRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONREQUEST,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:RecommendationRequest)
  })
_sym_db.RegisterMessage(RecommendationRequest)

FoodRecommendation = _reflection.GeneratedProtocolMessageType('FoodRecommendation', (_message.Message,), {
  'DESCRIPTOR' : _FOODRECOMMENDATION,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:FoodRecommendation)
  })
_sym_db.RegisterMessage(FoodRecommendation)

RecommendationResponse = _reflection.GeneratedProtocolMessageType('RecommendationResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONRESPONSE,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:RecommendationResponse)
  })
_sym_db.RegisterMessage(RecommendationResponse)

_RECOMMENDATIONS = DESCRIPTOR.services_by_name['Recommendations']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FOODCATEGORY._serialized_start=241
  _FOODCATEGORY._serialized_end=298
  _RECOMMENDATIONREQUEST._serialized_start=25
  _RECOMMENDATIONREQUEST._serialized_end=119
  _FOODRECOMMENDATION._serialized_start=121
  _FOODRECOMMENDATION._serialized_end=167
  _RECOMMENDATIONRESPONSE._serialized_start=169
  _RECOMMENDATIONRESPONSE._serialized_end=239
  _RECOMMENDATIONS._serialized_start=300
  _RECOMMENDATIONS._serialized_end=379
# @@protoc_insertion_point(module_scope)
